@extends('layouts.web')
@section('title')
Home
@endsection
@section('content')
@include('layouts.web.banner')
@include('layouts.web.about-us')
@include('layouts.web.last-services')
@include('layouts.web.for-zone')
@include('layouts.web.brands')
@include('layouts.web.footer')
@endsection